### ISSUE TITLE
Add immunity option for privileged players

### ISSUE THREAD

**Issue by crashzk** [falahati/veterans#6]
Would it be possible to implement an option to configure players with privileges immune to all verification of the plugin?

**Comment by falahati** [comment]
New cvars added:

`sm_veterans_excludereservedslots` = Should we exclude players that have a reserved slot from punishment? **(Default = Yes)**
`cvar_excludePrivileged` = Should we exclude privileged players from punishment? **(Default = No)**

I didn't test the latest version since I don't have a server anymore, so it would be great if someone could tell me if it works.
