### ISSUE TITLE
Development #1

### ISSUE THREAD

**Issue by ghost** [falahati/veterans#8]
- Would you add var so that it doesn't kick admins?
- For every player connected the server; can you add a chat message? The message will write the game hours information.
- https://haste.kgns.dev/yudujufito.cpp I use this plugin. The player who hides the game hours cannot login the server. For this, friends list and game details options should be set publicly. Previously, in your plugin, they could enter when the game hours was hidden.
- Since my domain is managed in cloudflare, the php file doesn't always work stably. https://haste.kgns.dev/ufohahipuw.cpp This is another plugin but it doesn't work. It may be more stable to use "api.steampowered.com" links instead of php file.

**Comment by falahati** [comment]
1. It shouldn't punish admins, there is a check for that in the plugin. But I just updated it so that it detects better hopefully; it will be in the next release. Currently `sm_veterans_excludeprivileged` can allow anybody who is privileged including the doners. You can test that.

2. Yeah, it should be possible. I didn't so that it doesn't inform users with public profiles that they can join if their profile is private and the `sm_veterans_kickprivate` is not active.

3. You should be able to do so if the `sm_veterans_kickprivate` is `0`. Please try the latest version and tell me if it works. You might also need to update the `queryPlaytime.php` file on your server.

4. Yeah, I also learned about that problem by user reports. You can probably [whitelist your server IP in Cloudflare](https://support.cloudflare.com/hc/en-us/articles/217074967-Configuring-IP-Access-Rules). It isn't possible for me since I don't know the IP address of all the servers using this plugin. BTW, the reason why I didn't use the server to do the final request was to offload the XML parsing to PHP which is easier. I go into solutions for this below.

-----------

I was going to make an issue to keep ideas for further development of this plugin, but since you already made this issue, I am going to hijack it :)

I was thinking about these; but unfortunately, they all need an API key:

* Query user info using [`http://api.steampowered.com/IPlayerService/GetOwnedGames/v1/?key=APIKEY&steamid=STEAMID&appids_filter[0]=730&format=vdf`](https://partner.steamgames.com/doc/webapi/IPlayerService#GetOwnedGames) instead of an offsite PHP file. This is possible only because SourcePawn contains a VDF parser internally.
* Query and check user's ban status using [`http://api.steampowered.com/ISteamUser/GetPlayerBans/v1/?key=APIKEY&steamids=STEAMID&format=vdf`](https://partner.steamgames.com/doc/webapi/ISteamUser#GetPlayerBans)
* Query and check user's profile country [`http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/?key=APIKEY&steamids=STEAMID&format=vdf`](https://partner.steamgames.com/doc/webapi/ISteamUser#GetPlayerSummaries)
* Query and check for user's XP and other game stats since 2018 at least [`http://api.steampowered.com/ISteamUserStats/GetUserStatsForGame/v2/?key=APIKEY&steamid=STEAMID&appid=730&format=vdf`](https://partner.steamgames.com/doc/webapi/ISteamUserStats#GetUserStatsForGame)
* Query and check user's steam profile level as you suggested in the other issue [`http://api.steampowered.com/IPlayerService/GetSteamLevel/v1/?key=APIKEY&steamid=STEAMID&format=vdf`](https://partner.steamgames.com/doc/webapi/IPlayerService#GetSteamLevel)
* Detect CSGO user-level #7

**Comment by KillerRoi** [comment]
So When are you adding these further developments? if you need servers to test it, DM me on Discord KillerRoi#6969
